In [313]:
import numpy as np
import glob
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [314]:
dat_paths = glob.glob("medium*.csv")
print(dat_paths)
#print(dat_paths[0])
data = [np.loadtxt(dat_path) for dat_path in dat_paths]
#data = np.loadtxt(dat_paths[0]) 

['medium0.csv', 'medium1.csv', 'medium10.csv', 'medium11.csv', 'medium12.csv', 'medium13.csv', 'medium14.csv', 'medium15.csv', 'medium16.csv', 'medium17.csv', 'medium18.csv', 'medium19.csv', 'medium2.csv', 'medium3.csv', 'medium4.csv', 'medium5.csv', 'medium6.csv', 'medium7.csv', 'medium8.csv', 'medium9.csv']


In [315]:
dat_paths = glob.glob("result_cells*.csv")
print(dat_paths)
#print(dat_paths[0])
recedata = [np.loadtxt(dat_path) for dat_path in dat_paths]
#data = np.loadtxt(dat_paths[0]) 

['result_cells0.csv', 'result_cells1.csv', 'result_cells10.csv', 'result_cells11.csv', 'result_cells12.csv', 'result_cells13.csv', 'result_cells14.csv', 'result_cells15.csv', 'result_cells16.csv', 'result_cells17.csv', 'result_cells18.csv', 'result_cells19.csv', 'result_cells2.csv', 'result_cells3.csv', 'result_cells4.csv', 'result_cells5.csv', 'result_cells6.csv', 'result_cells7.csv', 'result_cells8.csv', 'result_cells9.csv']


In [316]:
dat_paths = glob.glob("cell_vmax*.csv")
print(dat_paths)
#print(dat_paths[0])
vmaxdata = [np.loadtxt(dat_path) for dat_path in dat_paths]
#data = np.loadtxt(dat_paths[0]) 

['cell_vmax0.csv', 'cell_vmax1.csv', 'cell_vmax10.csv', 'cell_vmax11.csv', 'cell_vmax12.csv', 'cell_vmax13.csv', 'cell_vmax14.csv', 'cell_vmax15.csv', 'cell_vmax16.csv', 'cell_vmax17.csv', 'cell_vmax18.csv', 'cell_vmax19.csv', 'cell_vmax2.csv', 'cell_vmax3.csv', 'cell_vmax4.csv', 'cell_vmax5.csv', 'cell_vmax6.csv', 'cell_vmax7.csv', 'cell_vmax8.csv', 'cell_vmax9.csv']


In [317]:
dat_paths = glob.glob("new_cells*.csv")
print(dat_paths)
#print(dat_paths[0])
newcelldata = [np.loadtxt(dat_path) for dat_path in dat_paths]
#data = np.loadtxt(dat_paths[0]) 

['new_cells0.csv', 'new_cells1.csv', 'new_cells10.csv', 'new_cells11.csv', 'new_cells12.csv', 'new_cells13.csv', 'new_cells14.csv', 'new_cells15.csv', 'new_cells16.csv', 'new_cells17.csv', 'new_cells18.csv', 'new_cells19.csv', 'new_cells2.csv', 'new_cells3.csv', 'new_cells4.csv', 'new_cells5.csv', 'new_cells6.csv', 'new_cells7.csv', 'new_cells8.csv', 'new_cells9.csv']


In [318]:
dat_paths = glob.glob("bfsel-cells*.csv")
print(dat_paths)
#print(dat_paths[0])
bfsel_celldata = [np.loadtxt(dat_path) for dat_path in dat_paths]
#data = np.loadtxt(dat_paths[0]) 

['bfsel-cells0.csv', 'bfsel-cells1.csv', 'bfsel-cells10.csv', 'bfsel-cells11.csv', 'bfsel-cells12.csv', 'bfsel-cells13.csv', 'bfsel-cells14.csv', 'bfsel-cells15.csv', 'bfsel-cells16.csv', 'bfsel-cells17.csv', 'bfsel-cells18.csv', 'bfsel-cells19.csv', 'bfsel-cells2.csv', 'bfsel-cells3.csv', 'bfsel-cells4.csv', 'bfsel-cells5.csv', 'bfsel-cells6.csv', 'bfsel-cells7.csv', 'bfsel-cells8.csv', 'bfsel-cells9.csv']


In [342]:
bfsel_celldata[1][-1]

array([1.43500000e+03, 6.64991563e+07, 9.23769018e+01, 8.47728382e+01,
       2.52025564e+01, 2.13988545e+01, 9.44433508e+00, 1.11678268e+01,
       4.74519256e+00, 8.70296283e+00, 2.57386242e+01, 5.01633682e+00,
       6.69974980e+00, 3.91770504e+00, 5.23015582e+00, 1.19426030e+01,
       4.21112750e+00, 1.98912100e+01, 3.11587100e+00, 3.04258352e+00,
       2.73021608e+00, 2.44994102e+00, 1.90931786e+00, 1.95271010e+00,
       1.77036811e+00, 1.58871878e+00, 1.42573873e+00, 1.09839517e+00,
       0.00000000e+00, 1.03062290e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [319]:
recedata[1][-1]

array([1.43500000e+03, 1.78079424e+03, 2.42299632e+07, 2.96296936e+01,
       1.39626499e+02, 1.29465401e+01, 8.13279431e+00, 2.90862708e+00,
       7.49698178e+00, 4.35880081e+00, 4.64346865e+00, 3.19418875e+02,
       1.56809812e+00, 2.91528310e+00, 2.73466411e+00, 2.50370677e+00,
       4.81870129e+01, 2.09867626e+00, 1.80858480e+00, 1.75918752e+00,
       2.82022387e+00, 1.15364721e+00, 1.25577003e+00, 1.23613090e+00,
       1.13176858e+00, 0.00000000e+00, 0.00000000e+00, 1.17518233e+01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 6.10950091e+01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.62923078e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [331]:
recedata[0][1:][:]
    

array([[5.00000000e+00, 1.11448760e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+01, 1.24208260e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.50000000e+01, 1.38428566e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.42500000e+03, 6.76261203e+07, 9.39424170e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.43000000e+03, 6.70602710e+07, 9.31563709e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.43500000e+03, 6.64991563e+07, 9.23769018e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [320]:
bfsel_celldata[2][-1]

array([1.43500000e+03, 6.98890007e+03, 5.68885071e+04, 1.03276962e+05,
       6.80840023e+04, 1.08639500e+04, 7.67459086e+04, 1.34292341e+05,
       6.62330337e+04, 3.40176623e+03, 2.69545727e+07, 2.45141792e+04,
       1.36124372e+03, 2.08346866e+04, 8.53499673e+02, 7.61842113e+02,
       2.07017368e+03, 2.87006018e+03, 1.65535952e+02, 5.55530190e+02,
       2.31432958e+02, 1.15716423e+02, 3.04057998e+01, 2.89290971e+01,
       5.08106049e+02, 2.89290515e+01, 2.89290497e+01, 3.04821225e+01,
       9.27697449e+00, 9.96589766e+00, 7.18968149e+00, 3.71887836e+00,
       3.96684888e+00, 1.14623559e+01, 2.34722055e+00, 2.21402677e+00,
       1.83207573e+00, 1.98656428e+00, 2.57559497e+00, 2.38299008e+00,
       2.18897348e+00, 1.05756535e+00, 1.97664647e+00, 1.95528492e+02,
       1.21232203e+00, 5.50872930e+02, 1.26392532e+00, 6.00605680e+02,
       0.00000000e+00, 2.81533726e+00, 6.87955263e+01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.03731681e+01,
      

In [321]:
newcelldata

[array(1.),
 array([1.40000e+01, 6.64991e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00]),
 array([1.40000e+01, 6.90000e+01, 5.68000e+02, 1.03200e+03, 6.80000e+02,
        1.08000e+02, 7.67000e+02, 1.34200e+03, 6.62000e+02, 3.40000e+01,
        2.69545e+05, 2.45000e+02, 1.30000e+01, 2.08000e+02, 8.00000e+00,
        7.00000e+00, 2.00000e+01, 2.80000e+01, 1.00000e+00, 5.00000e+00,
        2.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 5.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.0

In [325]:
joinmedium = data[0]
for i in range(1,20):
    joinmedium = np.concatenate((joinmedium,data[i]), axis = 0)

In [326]:
np.savetxt("joinmedium.csv",joinmedium)

In [344]:
allday = 20
newcell = np.zeros((allday,2))
bfcell = np.zeros((allday,2))
Pop_fp = np.zeros((allday,2))
Pop_lp = np.zeros((allday,2))
agent_fp = np.zeros((allday,2))
agent_lp = np.zeros((allday,2))
for day in range(0,allday):

    Pop_fp[day][0] = day
    Pop_fp[day][1] = np.sum(recedata[day][0][:])
    #Pop_fp[day][1] = np.sum(newcelldata[day][:])
    #print(Pop_fp[day][:])
    
    newcell[day][0] = day
    newcell[day][1] = np.sum(newcelldata[day])
    
    bfcell[day][0] = day
    bfcell[day][1] = np.sum(bfsel_celldata[day][-1])
  
    Pop_lp[day][0] = day
    Pop_lp[day][1] = np.sum(recedata[day][287][:])
    #print(Pop_lp[day][:])
    
    agent_fp[day][0] = day
    agent_fp[day][1] = np.sum(recedata[day][0][:]>0.0)
    #print(agent_fp[day][:])
    
    agent_lp[day][0] = day+0.5
    agent_lp[day][1] = np.sum(recedata[day][287][:]>0.0)
    #print(agent_lp[day][:])

    
print(bfcell)
print(newcell)
print()
ratio1 = np.zeros((allday,1))
for day in range (0,allday):
    #print(newcell[day][1])
    #print(Pop_lp[day-1][1])
    ratio1[day][0] = (newcell[day][1]/bfcell[day][1])*100
print(ratio1)

#print(newcell)
#print(Pop_lp[:,1])

[[0.00000000e+00 1.00001000e+02]
 [1.00000000e+00 6.65009539e+07]
 [2.00000000e+00 2.75394581e+07]
 [3.00000000e+00 2.72752698e+07]
 [4.00000000e+00 2.81030077e+07]
 [5.00000000e+00 2.42231109e+07]
 [6.00000000e+00 3.08416613e+07]
 [7.00000000e+00 2.60708077e+07]
 [8.00000000e+00 2.44301753e+07]
 [9.00000000e+00 5.41276262e+07]
 [1.00000000e+01 3.00284949e+07]
 [1.10000000e+01 3.51451904e+07]
 [1.20000000e+01 2.42338548e+07]
 [1.30000000e+01 2.73185304e+07]
 [1.40000000e+01 2.81357796e+07]
 [1.50000000e+01 3.03641669e+07]
 [1.60000000e+01 2.56935537e+07]
 [1.70000000e+01 2.80765140e+07]
 [1.80000000e+01 2.79461699e+07]
 [1.90000000e+01 3.04282894e+07]]
[[0.00000e+00 1.00000e+00]
 [1.00000e+00 6.65005e+05]
 [2.00000e+00 2.75377e+05]
 [3.00000e+00 2.72737e+05]
 [4.00000e+00 2.81012e+05]
 [5.00000e+00 2.42219e+05]
 [6.00000e+00 3.08402e+05]
 [7.00000e+00 2.60695e+05]
 [8.00000e+00 2.44289e+05]
 [9.00000e+00 5.41260e+05]
 [1.00000e+01 3.00267e+05]
 [1.10000e+01 3.51430e+05]
 [1.20000e+01 2

In [332]:
Pop_lp[12][1]

27318530.41133002

In [333]:
newcell[13][1]

273179.0

In [334]:
(newcell[13][1]/Pop_lp[12][1])*100

0.9999769236733995

In [335]:
Pop_lp[11][1]

53386461.950872354

In [336]:
newcell[12][1]

242334.0

In [273]:
newcell

array([[0.00000e+00, 1.00000e+00],
       [1.00000e+00, 6.65005e+05],
       [2.00000e+00, 2.42334e+05],
       [3.00000e+00, 2.73179e+05]])

In [258]:
Pop_lp

array([[0.00000000e+00, 6.65009539e+07],
       [1.00000000e+00, 2.42338548e+07],
       [2.00000000e+00, 2.73185304e+07],
       [3.00000000e+00, 2.81357796e+07]])

In [102]:
newcelldata

[array(1.), array([1.4000e+01, 6.6499e+05, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00]), array([1.40000e+01, 4.00000e+00, 2.27579e+05, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 3.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,

In [119]:
np.sum(newcelldata[1])

665009.0

In [120]:
ratio = np.sum(newcelldata[1])/np.sum(recedata[0][287][:])*100.0

In [121]:
ratio

0.9999929780225045